spring:
  datasource:
    username: root
    password: aixiaoju11
    url: jdbc:mysql://123.57.93.65:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    check-template-location : true
    suffix: .html
  resources:
      static-locations: classpath:/static/, classpath:/templates/
  redis:
    database: 0
    timeout: 0
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
  rabbitmq:
    host: 127.0.0.1
    password: guest
    username: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
        default-requeue-rejected: true
server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: com/travel/function/mapper/*.xml
  type-aliases-package: com.travel.function.entity,com.travel.function.vo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pageCache:
  enable: true
logging:
  level:
    com.cet.diagsyscloud.system.dao: DEBUG